name: Compile Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Configuring git environment.
         run: |
            git config --global user.name xiihaiqal
            git config --global user.email admin@kingkongvpn.com.my

       - name: Building Kernel.
         run: |
             git clone --depth 1 https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/kernel_xiaomi_ginkgo.git -b fourteenKSU kernel
             cd kernel
             chmod 777 build.sh
             ./build.sh

       - name: Uploading ZIP.
         run: |
             cd kernel
             curl -T *.zip https://pixeldrain.com/api/file/ && echo ""
